//contains helper functions 
//do not edit this file 
//these functions are actually function templates
//and can work with different datatypes
#pragma once
#ifndef HELPERH
#define HELPERH
#include <iostream>
#include <string>
#include <sstream>
#include <fstream>
using namespace std;

struct colors {
	const string pink = "Pink";
	const string purple = "Purple";
	const string indigo = "Indigo";
	const string red = "Red";
	const string orange = "Orange";
	const string gold = "Gold";
	const string yellow = "Yellow";
	const string khaki = "Khaki";
	const string greenyellow = "GreenYellow"; 
	const string lime = "Lime";
	const string green = "Green";
	const string teal = "Teal";
	const string aqua = "Aqua"; 
	const string cyan = "Cyan";
	const string blue = "Blue";
	const string navy = "Navy";
	const string brown = "Brown";
	const string maroon = "Maroon";
	const string white = "White";
	const string gray = "Gray";
	const string black = "Black";
}colors;

template <class T>
string addtostring(string s, T num)
{
	ostringstream ss;
	ss << s << num;
	string toret(ss.str());
	return toret;
}

template <class T>
string addtostring(string s, T num, string s1, T num1, string s2)
{
	ostringstream ss;
	ss << s << num << s1 << num1 << s2;
	string toret(ss.str());
	return toret;
}


#endif
