#include "svgFile.h"				//include the appropriate header file
#include "helper.h"					//includes helper functions etc

//DO NOT EDIT THIS FILE

string SVGfile::makesvgheader()
{
	string svgheader = addtostring("<svg width=\"", width, "\" height=\"", height, "\">");
	return svgheader;
}

void SVGfile::initvars()
{
	header = "<html>"
		"<body>"
		"<h1>" + title + "</h1>";

	header = header + makesvgheader();
	footer = "</svg>"
		"</body>"
		"</html>";
	body = "";
}

SVGfile::SVGfile()
{
	width = 100; 
	height = 100;
	title = "Test SVG";
	initvars();
}

SVGfile::SVGfile(float width, float height)
{
	this->width = width; 
	this->height = height;
	title = "Test SVG"; 
	initvars();
}

SVGfile::SVGfile(string title)
{
	width = 100; 
	height = 100; 
	this->title = title;
	initvars();
}

SVGfile::SVGfile(string t, float w, float h)
{
	width = w; 
	height = h; 
	title = t; 
	initvars();
}
void SVGfile::addtofile(string s)
{
	body += s;
}
void SVGfile::writefile(string fn)
{
	string filetowrite = header + body + footer;

	std::ofstream out(fn);
	out << filetowrite;
	out.close();
}
void SVGfile::openfile(string fn)
{
	system(fn.c_str());
}
void SVGfile::testempty()
{
	body = "<circle cx = \"50\" cy = \"50\" r = \"40\" stroke = \"green\" stroke - width = \"4\" fill = \"yellow\"/>";
	writefile(); 
	openfile();
}